# if-Else

In [ ]:
score = float(input("Enter your score: "))

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
elif score >= 60:
    print("Grade: D")
else:
    print("Grade: F")


# Loops

For

In [ ]:
for number in range(1, 11):
    if number % 5 == 0:
        print(f"{number} is a multiple of 5")
    elif number % 2 == 0:
        print(f"{number} is even")
    else:
        print(f"{number} is odd")


While

In [ ]:
counter = 1

while counter <= 20:
    if counter % 5 == 0:
        print(f"{counter} is a multiple of 5")
    elif counter % 2 == 0:
        print(f"{counter} is even")
    else:
        print(f"{counter} is odd")

    counter += 3  # Increment the counter by 3

# loop control statement

1.   break: Used to exit a loop prematurely based on a condition.
2.   continue: Used to skip the current iteration of a loop based on a condition.
3.   else (with loops): Executed after a loop completes all its iterations without encountering a break statement.









In [2]:

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for i in numbers:
    # Check if the number is even
    if i % 2 == 0:
        print(f"Skipping even number: {i}")
        continue  # Skip to the next iteration if the number is even

    # Check if the number is greater than 6
    if i > 6:
        print(f"Exiting loop at number: {i}")
        break  # Exit the loop if the number is greater than 5

    print(f"Processing number: {i}")

else:
    # This block executes if the loop completes all iterations without encountering a break statement
    print("Loop completed successfully without encountering a break statement")


Processing number: 1
Skipping even number: 2
Processing number: 3
Skipping even number: 4
Processing number: 5
Skipping even number: 6
Exiting loop at number: 7


# Function

In [3]:
def greet(name):
    print("Hello,", name, "!")

greet("Nik")


Hello, Nik !


In [5]:
def add(a, b):
    return a + b

result = add(3, 4) # to store output value of functon
print(result). # to display anything

7


**list in Python**


In [ ]:
Mylist = [1,2,3,4,"nik","N", "i"]
numlist = [0,1,2,3,4,5,6,7,8,9,10]

print(Mylist)
# in pyhton indexing start from 0
#lower bound value includes the value in list whereas uperbound doest count in the list .
print(numlist[0:3])
#alternative entry on the list
print(numlist[::2])

[1, 2, 3, 4, 'nik', 'N', 'i']
[0, 1, 2]
[0, 2, 4]


In [ ]:
#to print 3rd alternative element in the list
print(Mylist[0:8:3])

# in python there is 2 type of indexing if you go left to right it will ne 0,1,2,3
# if you go right to left then -1,-2,-3,-4
print(Mylist[0:-1])

# to print list in reverese manner
print (Mylist[::-1])

[1, 4, 'i']
[1, 2, 3, 4, 'nik', 'N']
['i', 'N', 'nik', 4, 3, 2, 1]


# data addition in List

In [ ]:
fruits = ["Banana","Apple"]

fruits.append("Mango")

print(fruits)
#with appends method data will be added on the last position


['Banana', 'Apple', 'Mango']


In [ ]:
#addition of 2 List

List1 = [1,2,3,4,5]
List2 = [1,2,5,9]

print(List1 + List2)

#if I multiply List with X(integer) it will add itself X times
print(List1*2)

[1, 2, 3, 4, 5, 1, 2, 5, 9]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#Extend method

# if we wont to add List 2 in list 1 then we can use Extend method
List1 = [1,2,3,4,5]
List2 = [1,2,5,9]
List1.extend(List2)
print(List1)

#if we use append method here it will add whole list2 in list 1
List1 = [1,2,4,5]
List2 = [7,5,9]

List1.append(List2)
print(List1)


[1, 2, 3, 4, 5, 1, 2, 5, 9]
[1, 2, 4, 5, [7, 5, 9]]


In [ ]:
#If we wont to add data on specific index we just need to Use insert

fruits1 = ["Banana","Apple","cherry","grapes"]

fruits1.insert(1,"Mango")
print(fruits1)

#whe we are looking to find any postion for any element in List
print(fruits1.index("cherry"))

['Banana', 'Mango', 'Apple', 'cherry', 'grapes']
3


# Data Deletion in list

In [ ]:
names = ["a","b","c","d","e","f"]

#If we just want to remove any element from List from any position  we can use POP method

names.pop(2)
print(names)

#del function also works the same

del names[1]
print(names)

['a', 'b', 'd', 'e', 'f']
['a', 'd', 'e', 'f']


In [ ]:
fruits = ["Apple", "Banana","grapes", "Mango", "strawberry"]

#if we want to remove perticulal element from list then we use Remove

fruits.remove("Mango")
print(fruits)
# if we have 2 mango in the List then it will remove only first one

fruits = ["Apple","Mango","Banana","grapes", "Mango", "strawberry"]

fruits.remove("Mango")
print(fruits)

# Remove all occurrences of "Mango" using a loop
fruits = ["Apple","Mango","Banana","grapes", "Mango", "strawberry"]

while "Mango" in fruits:
    fruits.remove("Mango")

print(fruits)

['Apple', 'Banana', 'grapes', 'strawberry']
['Apple', 'Banana', 'grapes', 'Mango', 'strawberry']
['Apple', 'Banana', 'grapes', 'strawberry']


**Other Function related to LIST**

In [ ]:
#Count Function
fruits = ["Apple","Mango","Banana","grapes", "Mango", "strawberry"]

print(fruits.count("Mango"))

#Len Function to find the Length of List

print(len(fruits))

#Sort function (it actualy sorts original list)

fruits.sort()
print(fruits)

#if you dont Want to sort actial List and want sorted element for output
fruits = ["Apple","Mango","Banana","grapes", "Mango", "strawberry"]
print(sorted(fruits))
print(fruits)

#clear (will remove all element from list)
fruits.clear()
print(fruits)

# what if we want duplicate list # Copy
fruits = ["Apple","Mango","Banana","grapes", "Mango", "strawberry"]
new_fruits = fruits.copy()
print(new_fruits)

2
6
['Apple', 'Banana', 'Mango', 'Mango', 'grapes', 'strawberry']
['Apple', 'Banana', 'Mango', 'Mango', 'grapes', 'strawberry']
['Apple', 'Mango', 'Banana', 'grapes', 'Mango', 'strawberry']
[]
['Apple', 'Mango', 'Banana', 'grapes', 'Mango', 'strawberry']


# join and Split method

In [ ]:
#split
info = "Nikhil 24 Trent MBDA"

print(info.split())

a= "nikhilbhail"
print(a.split("i"))

name, age, university, course = "Nikhil,24,Trent,MBDA".split(",")

print(age)


#Join method
detail = ['Nikhil', "Nakum"]
print((" ".join(detail)))

['Nikhil', '24', 'Trent', 'MBDA']
['n', 'kh', 'lbha', 'l']
24
Nikhil Nakum


In [ ]:
numbers = [1,4,5,7,8,10,34]
print(min(numbers))
print(max(numbers))
print(sum(numbers))


1
34


NameError: name 'avg' is not defined

# Difference Between List and Array in Python


[List vs Array](https://www.geeksforgeeks.org/difference-between-list-and-array-in-python/)

# Tuples

Tuples are faster than list and immutable.

In [ ]:
#methods that we can use in tuples

days = ("monday","tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")

print(days.count("monday"))
print(days.index("Wednesday"))
print(len(days))

print(days[1:7:2])

1
2
7
('tuesday', 'Thursday', 'Saturday')


In [ ]:
one = (1) # is not tuples
onee = (1,)  #this is tuples
line = "ase","juk","folck"  #tuples

**Tuple unpacking**

In [ ]:
band = ("Alex carry", "Mitchal starc", "travis head")
drummer , guitarist , flutter = band
print(drummer)

Alex carry


**List in tuples**

In [ ]:
tuppp = ("pochinki","picado",["ruins","dino park"])

#we can actually change list inside the tuples
tuppp[2].pop()
print(tuppp)


('pochinki', 'picado', ['ruins'])
('pochinki', 'picado', ['ruins'], 'pochinki', 'picado', ['ruins'])


***list to tuples <>***

In [ ]:
num = [1,2,3,4,5,6,7]

num = tuple(num)

print(num)

num = list(num)

print(num)

(1, 2, 3, 4, 5, 6, 7)
[1, 2, 3, 4, 5, 6, 7]


# Set

unordered(no indexing) collaction of unique items(no repetation)

we can not store tuples, list or dictionary in Set

In [ ]:
s = {3,4,2,1,4}

print(s)

#s[1] will gives us error

{1, 2, 3, 4}


In [ ]:
#how to remove duplicate number using set

l = [1,2,3,4,1,27,2,6,4,3,2,3,8,5,6,3,9,7,7,2,9]

l =list(set(l))
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 27]


**Set manipulation**

In [ ]:
s = {1,2,3}
s.add(5)
s.add(1)

print(s)

s.remove(1)
#s.remove(6) # this will gives us error
print(s)

s.discard(6)  #this will not give us error
print(s)

s.clear()
print(s)

s1 = {1,1.0,2,4,"stringgg"}
print(s1)

{1, 2, 3, 5}
{2, 3, 5}
{2, 3, 5}
set()
{'stringgg', 2, 4, 1}


We can use If-else and loops

**UNION and INTERSACTION**

In [ ]:
s1 ={1,2,3,5,6}
s2 ={2,3,6,7,9}

#union
print(s1 | s2)

#intersaction
print(s1 & s2)


{1, 2, 3, 5, 6, 7, 9}
{2, 3, 6}


# Dictionary

it comes with keys and associated value with it.

In [ ]:
#create

user = {"name" : "Nikhil", "Age" : 24 }
#OR
user2 = dict(Name = "NIK", Age = 23)
print(user)
print(user2)

print(user["name"])

{'name': 'Nikhil', 'Age': 24}
{'Name': 'NIK', 'Age': 23}
Nikhil


In [ ]:
user_info = {"name" : "Nik"}
user_info["name"] = "Nikhil"
user_info["Movies"] = ["FSG","ERF"]

print(user_info)

{'name': 'Nikhil', 'Movies': ['FSG', 'ERF']}


If- Else

In [ ]:
#to check key in dictionary
if "name" in user_info:
  print("Present")
else:
  print("Not present")

#to check value in dictionary

if "Nikil" in user_info.values():
  print("Present")
else:
  print("Not here")

Present
Not here


In [ ]:
#All keys in dictionary
for i in user_info:
  print(i)
#All values in dictionary
for j in user_info.values():
  print(j)

name
Movies
Nikhil
['FSG', 'ERF']


Data manipulations in dictionary

In [ ]:
user_info = {'name': 'Nikhil', 'Movies': ['FSG', 'ERF']}
user_info["Age"] = 30

print(user_info)

user_info.pop("Movies")
print(user_info)

#if we randomaly remove any item is popitem():


more_info = dict(IELTS = 7 , GPA = 3.93)

user_info.update(more_info)

print(user_info)

{'name': 'Nikhil', 'Movies': ['FSG', 'ERF'], 'Age': 30}
{'name': 'Nikhil', 'Age': 30}
{'name': 'Nikhil', 'Age': 30, 'IELTS': 7, 'GPA': 3.93}


To be continued from 119/120

# Numpy in Python

Faster then list bcz its binding with c programming
1-d array : Vector
2-d array : matrix
n-d array : tensor

In [ ]:
import numpy as np

numbers = [1,2,3,4.0]

numbers = np.array(numbers)
print(numbers)

numbers.ndim #dimension
numbers.shape #(row, column)
numbers.dtype #datatype of element in array

numbers.size #length or total elements



[1. 2. 3. 4.]


4

In [ ]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.diag([5,-3,2])
arr

#if we are looking too get just diagonal element from given matrix then
diangonal = np.diag(arr)
diangonal

array([ 5, -3,  2])

In [ ]:
# number range  generator.

arr = np.arange(1,5,0.5) #(Lower,high, difference)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
#random integer number generator.

arr = np.random.randint(1,12,4) #(Lower,high, n)
arr

array([ 2, 11,  3,  3])

In [ ]:
arr = np.random.rand(5,2) #(float value between 0 to 1, (nrow,ncol)
arr

array([[0.24527926, 0.52985384],
       [0.67451062, 0.39903184],
       [0.7837913 , 0.27457555],
       [0.85678512, 0.79789482],
       [0.59464555, 0.6866588 ]])

In [ ]:
arr = np.random.randn(5) #Normal distribution,(nrow, ncol)
arr

array([-0.8736469 ,  0.8982189 , -1.3154773 ,  0.74683068,  0.6373491 ])

**array reshapping**

In [ ]:
arr1 = np.random.randint(1,10,32)
arr1
arr2 = arr1.reshape(4,2,4)
arr2

arr3 = arr2.reshape(4,8)
arr3

array([[2, 1, 7, 2, 9, 7, 7, 1],
       [6, 9, 9, 7, 6, 7, 9, 7],
       [3, 1, 4, 9, 2, 4, 7, 9],
       [9, 9, 3, 5, 2, 6, 2, 9]])

In [ ]:
#Let suppose we dont know ncol or nrow instead we write -1 it will count accordingly
arr5 = arr1.reshape(-1,4,4) #-1 counts as 2 => 4*4*2 =32
arr5

array([[[2, 1, 7, 2],
        [9, 7, 7, 1],
        [6, 9, 9, 7],
        [6, 7, 9, 7]],

       [[3, 1, 4, 9],
        [2, 4, 7, 9],
        [9, 9, 3, 5],
        [2, 6, 2, 9]]])

**Set_seed**

In [ ]:
np.random.seed(42) #Tell the computer to generate the same random numbers every time.

random_numbers = np.random.rand(5)
random_numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

## Indexing and slicing

In [ ]:
arr_num = np.array([1,2,3,4,5,6,1,23,4,5])
arr_num[5]
#same indexing as a List

#e.g -1 for last element

arr_num[5:-1:2]  #[lower: upper : difference]

array([ 6, 23])

In [ ]:
#How about 2d array

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

#Lets find postion of 6
matrix[1][2]

matrix[2][0:2]

matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[1:,1:] #mostaly use this for slicing

array([[5, 6],
       [8, 9]])

**View vs Copy**

In [ ]:
arr = np.array([1,4,2,6,3,4,9,7])
samp_arr = arr[1:5]

print(samp_arr)

samp_arr[:] = 0 #this will change the original array as well.

print(arr)

samp_arr = arr[1:5].copy() # this will locate in different memory.

samp_arr[:] = 2

print(arr)


[4 2 6 3]
[1 0 0 0 0 4 9 7]
[1 0 0 0 0 4 9 7]


Conditional Selection(Filter)

In [ ]:
num1 = np.arange(1,11)

print(num1[num1 > 5])
print(num1[num1%2 == 1])

[ 6  7  8  9 10]
[1 3 5 7 9]


**Arithmetic Operations**

In [ ]:
print(num1 + 2)
print(num1 ** 2)
num2 = np.arange(11,21)
print(num1+num2) #shape and size should be same
print(num1*num2)


[ 3  4  5  6  7  8  9 10 11 12]
[  1   4   9  16  25  36  49  64  81 100]
[12 14 16 18 20 22 24 26 28 30]
[ 11  24  39  56  75  96 119 144 171 200]


array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [ ]:
#dot product

a = np.array([[1,2],[2,4]])
b = a = np.array([[1,3],[2,8]])
a.dot(b)

[[1 3]
 [2 8]]


array([[ 7, 27],
       [18, 70]])

In [ ]:
np.sum(num1)
np.median(num1)
np.mean(num1)
np.max(num1)
np.argmax(num1)  #giving us position of max element in array
np.std(num1) #standard deviation

np.sqrt(num1)
np.exp(num1)

np.sin(num1)
np.tan(num1)

np.linspace(1,10, 20) # (lower,upper, how many equldistance number we want )

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

**AXIS**

NumPy's axis specifies direction (rows or columns) for operations on arrays

In [ ]:
arr = np.array([[5, 2, 6],
                [9, 8, 4],
                [7,2,3]])

# max along axis 0 (columns)
result = np.max(arr, axis=0)
print(result)
# sum along axis 1 (rows)
result = np.sum(arr, axis=1)
print(result)
# product along axis 1 (rows)
result = np.prod(arr, axis=1)
print(result)

#cumulative Sum
print(np.cumsum(arr))
np.cumsum(arr, axis = 0) #column wise and just column

[9 8 6]
[13 21 12]
[ 60 288  42]
[ 5  7 13 22 30 34 41 43 46]


array([[ 5,  2,  6],
       [14, 10, 10],
       [21, 12, 13]])

### Axis In a 3D NumPy array:

axis=0:
Operations work along the first axis (slices across multiple matrices).

axis=1:
Operations work along the second axis (operate within each matrix).

axis=2:
Operations work along the third axis (operate within each row).

In [ ]:

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]],

                   [[13, 14, 15],
                    [16, 17, 18]]])
print("Original 3D Array:")
print(arr_3d)
# Sum along axis 0 (slices across matrices) each  element sum in 2D erray like 6+12+18
sum_axis_0 = np.sum(arr_3d, axis=0)

# Sum along axis 1 (operate within each matrix) #each 2D matix column
sum_axis_1 = np.sum(arr_3d, axis=1)

# Sum along axis 2 (operate within each row)
sum_axis_2 = np.sum(arr_3d, axis=2)

print("\nSum along Axis 0:")
print(sum_axis_0)

print("\nSum along Axis 1:")
print(sum_axis_1)

print("\nSum along Axis 2:")
print(sum_axis_2)

Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

Sum along Axis 0:
[[21 24 27]
 [30 33 36]]

Sum along Axis 1:
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]

Sum along Axis 2:
[[ 6 15]
 [24 33]
 [42 51]]


**Shuffle & Unique**

In [ ]:
import numpy as np
np.random.seed(3)

arr = np.random.randint(1, 11, 15)
print("Original array:", arr)

np.random.shuffle(arr)
print("Shuffled array:", arr)

print(np.unique(arr).size)
np.unique(arr, return_counts=True, return_index =True)

Original array: [ 9 10  4  9  9  1  6  4 10 10  6  8  7  1  5]
Shuffled array: [ 9  1  8  9 10  9  5  4  6 10  6 10  4  1  7]
8


(array([ 1,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  7,  6,  8, 14,  2,  0,  4]),
 array([2, 2, 1, 2, 1, 1, 3, 3]))

**Horizontal anad Vertical stacking**

In [ ]:
np.random.seed(33)
matrix1 = np.random.randint(1, 11, 9).reshape(3,3)
matrix2 = np.random.randint(5, 16, 9).reshape(3,3)

#Horizontal stacking
np.hstack((matrix1,matrix2))

#Vertical stacking
np.vstack((matrix1,matrix2))

#1-D Array
array1 = np.random.randint(2, 11, 5)
array2 = np.random.randint(21, 31, 5)

np.hstack((array1,array2))
np.vstack((array1,array2))


array([[ 8,  8,  2,  6, 10],
       [29, 24, 28, 30, 24]])

# Let start with pandas in Python 3.0